name: yew CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    
    - name: Install Trunk
      uses: jetli/trunk-action@v0.4.0
      with:
        version: latest
    
    - name: Add wasm target
      run: |
        rustup target add wasm32-unknown-unknown
    
    - name: Cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check
    
    - name: Build the Rust WASM app and all of its assets
      run: trunk build --public-url ${{ github.event.repository.name }} --release
    
    - name: Setup Pages
      uses: actions/configure-pages@v3
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./dist
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
